name: Validation Fabric
run-name: Validation Fabric PR #${{ github.event.pull_request.number }} @ ${{ github.event.pull_request.head.sha }}

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  validate:
    uses: Enchantus/validation-fabric/.github/workflows/validate.yml@v1
    with:
      tooling-ref: v1
      base: ${{ github.event.pull_request.base.sha }}
      head: ${{ github.event.pull_request.head.sha }}
      head-repository: ${{ github.event.pull_request.head.repo.full_name }}
